name: Verify build

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  call-workflow-in-another-repo:
    uses: hotwax/dxp-components/.github/workflows/common-pull-request.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}
